#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7 and revised by Yunsen Zhang at 06/05/2022

# This folder contains GROMACS formatted CHARMM36 force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx21  mdrun -ntomp 1

init=step5_ready
rest_prefix=step5_ready
mini_prefix=step6.0_minimization
equi_prefix=step6.%d_equilibration
prod_prefix=step7_production
prod_step=step7

# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.
gmx  grompp -f ${mini_prefix}.mdp -o ${mini_prefix}.tpr -c ${init}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 99
gmx  mdrun -v -deffnm ${mini_prefix} -ntmpi 1 -ntomp 8



# Equilibration
cnt=1
cntmax=6

while [ $cnt -le $cntmax ]
do
    pcnt=`expr $cnt - 1`
    istep=`printf ${equi_prefix} ${cnt}`
    pstep=`printf ${equi_prefix} ${pcnt}`
    if [ ${cnt} == 1 ]; then pstep=${mini_prefix};fi

    gmx  grompp -f ${istep}.mdp -o ${istep}.tpr -c ${pstep}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 99
    gmx  mdrun -v -deffnm ${istep} -ntmpi 1 -ntomp 12 -gpu_id 0 -update gpu
    let cnt++
done

# Production
cnt=1
cntmax=1

while [ $cnt -le $cntmax ]
do
    pcnt=`expr ${cnt} - 1`
    istep=${prod_step}_${cnt}
    pstep=${prod_step}_${pcnt}

	if [ ${cnt} == 1 ] 
	then
        pstep=`printf ${equi_prefix} 6`
        gmx  grompp -f ${prod_prefix}.mdp -o ${istep}.tpr -c ${pstep}.gro -p topol.top -n index.ndx -maxwarn 99 -r ${pstep}.gro
	else
        gmx  grompp -f ${prod_prefix}.mdp -o ${istep}.tpr -c ${pstep}.gro -t ${pstep}.cpt -p topol.top -n index.ndx -maxwarn 99 -r ${pstep}.gro
	fi
        gmx  mdrun -v -deffnm ${istep} -ntmpi 1 -ntomp 8 -gpu_id 0 -update gpu
    
    let cnt++

done
